import { useState } from 'react';
import { FileText, Download, Calculator, AlertCircle } from 'lucide-react';
import type { ReconciledItem, SummaryStats } from '../App';

interface Props { data: ReconciledItem[] | null; summary: SummaryStats | null; }

export default function Gstr3bDraft({ data, summary }: Props) {
  const [fy] = useState('2025-26');
  const [month] = useState(new Date().toLocaleString('en-IN', { month: 'long' }));

  if (!data || !summary) {
    return (
      <div className="glass-card p-16 flex flex-col items-center justify-center text-center">
        <FileText size={48} style={{ color: 'var(--text-muted)', marginBottom: 16 }} />
        <h3 className="text-lg font-bold" style={{ color: 'var(--text-primary)' }}>No reconciliation data</h3>
        <p className="text-sm mt-2" style={{ color: 'var(--text-muted)', maxWidth: 380 }}>Run a GSTR-2B reconciliation first. The GSTR-3B draft will be auto-calculated from your reconciled data.</p>
      </div>
    );
  }

  const fmt = (n: number) => new Intl.NumberFormat('en-IN', { style: 'currency', currency: 'INR', maximumFractionDigits: 2 }).format(n);
  const round2 = (n: number) => Math.round(n * 100) / 100;

  // Calculate from reconciled data
  const itcClaimable = summary.itcClaimable || { igst: 0, cgst: 0, sgst: 0 };
  const itcLeakage   = summary.itcLeakage   || { igst: 0, cgst: 0, sgst: 0 };

  // 3B table 4 — ITC available
  const table4 = {
    a5_igst: round2(itcClaimable.igst),
    a5_cgst: round2(itcClaimable.cgst),
    a5_sgst: round2(itcClaimable.sgst),
    reversals: round2(itcLeakage.igst + itcLeakage.cgst + itcLeakage.sgst),
    net_itc_igst: round2(itcClaimable.igst - itcLeakage.igst),
    net_itc_cgst: round2(itcClaimable.cgst - itcLeakage.cgst),
    net_itc_sgst: round2(itcClaimable.sgst - itcLeakage.sgst),
  };

  const rows3B = [
    { table: '3.1(a)', head: 'Outward taxable supplies (other than zero rated, nil and exempted)', igst: 0, cgst: 0, sgst: 0, cess: 0, editable: true },
    { table: '3.1(b)', head: 'Outward taxable supplies (zero rated)', igst: 0, cgst: 0, sgst: 0, cess: 0, editable: true },
    { table: '3.1(c)', head: 'Other outward supplies (nil, exempted)', igst: 0, cgst: 0, sgst: 0, cess: 0, editable: true },
    { table: '3.1(d)', head: 'Inward supplies (liable to reverse charge)', igst: round2(data.filter(r => (r as any).category === 'RCM').reduce((s, r) => s + r.gstrAmount, 0)), cgst: 0, sgst: 0, cess: 0, editable: false },
    { table: '4(A)(5)', head: 'ITC Available — All other ITC', igst: table4.a5_igst, cgst: table4.a5_cgst, sgst: table4.a5_sgst, cess: 0, editable: false },
    { table: '4(D)(2)', head: 'ITC Reversed — Reversals/Leakage', igst: round2(itcLeakage.igst), cgst: round2(itcLeakage.cgst), sgst: round2(itcLeakage.sgst), cess: 0, editable: false },
    { table: '4(C)', head: 'Net ITC Available', igst: table4.net_itc_igst, cgst: table4.net_itc_cgst, sgst: table4.net_itc_sgst, cess: 0, editable: false, isTotal: true },
  ];

  const downloadDraft = () => {
    const lines = [
      `GSTR-3B Draft — ${month} ${fy}`,
      `Generated by GSTSync on ${new Date().toLocaleDateString('en-IN')}`,
      '',
      'Table,Description,IGST,CGST,SGST,Cess',
      ...rows3B.map(r => `${r.table},"${r.head}",${r.igst},${r.cgst},${r.sgst},${r.cess}`),
    ];
    const blob = new Blob([lines.join('\n')], { type: 'text/csv' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url; a.download = `GSTR3B_Draft_${month}_${fy}.csv`; a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div>
      <div className="flex items-center justify-between mb-6">
        <div>
          <h2 className="text-xl font-bold" style={{ color: 'var(--text-primary)' }}>GSTR-3B Draft</h2>
          <p className="text-sm mt-1" style={{ color: 'var(--text-muted)' }}>
            Pre-filled from reconciled data · {month} {fy} · Review before filing
          </p>
        </div>
        <button className="btn-primary" onClick={downloadDraft}><Download size={16} /> Download CSV</button>
      </div>

      {/* Summary KPIs */}
      <div className="grid grid-cols-3 gap-5 mb-6">
        {[
          { label: 'ITC Claimable (IGST)', val: fmt(table4.a5_igst), color: '#10b981' },
          { label: 'ITC Claimable (CGST+SGST)', val: fmt(table4.a5_cgst + table4.a5_sgst), color: '#0ea5e9' },
          { label: 'ITC Leakage Gap', val: fmt(itcLeakage.igst + itcLeakage.cgst + itcLeakage.sgst), color: itcLeakage.igst > 0 ? '#ef4444' : '#10b981' },
        ].map((k, i) => (
          <div key={i} className="glass-card p-5">
            <p className="text-xs font-medium mb-2" style={{ color: 'var(--text-muted)' }}>{k.label}</p>
            <p className="text-2xl font-bold" style={{ color: k.color }}>{k.val}</p>
          </div>
        ))}
      </div>

      {/* 3B Table */}
      <div className="glass-card overflow-hidden">
        <div className="flex items-center gap-2 px-6 py-4" style={{ borderBottom: '1px solid var(--border-subtle)' }}>
          <Calculator size={18} style={{ color: 'var(--text-accent)' }} />
          <h3 className="font-semibold" style={{ color: 'var(--text-primary)' }}>GSTR-3B Pre-filled Values</h3>
          <span className="ml-auto text-xs px-2 py-1 rounded-full font-medium" style={{ background: 'rgba(16,185,129,0.12)', color: '#10b981' }}>Auto-calculated</span>
        </div>
        <div className="overflow-x-auto">
          <table className="w-full text-sm" style={{ borderCollapse: 'separate', borderSpacing: 0 }}>
            <thead>
              <tr style={{ background: 'var(--bg-hover)' }}>
                {['Table', 'Description', 'IGST (₹)', 'CGST (₹)', 'SGST (₹)', 'Cess (₹)'].map(h => (
                  <th key={h} className="px-4 py-3 text-left text-xs font-semibold uppercase tracking-wider"
                    style={{ color: 'var(--text-muted)', borderBottom: '1px solid var(--border-subtle)', whiteSpace: 'nowrap' }}>{h}</th>
                ))}
              </tr>
            </thead>
            <tbody>
              {rows3B.map((r, i) => (
                <tr key={i} className="tbl-row" style={r.isTotal ? { background: 'var(--bg-active)', fontWeight: 700 } : {}}>
                  <td className="px-4 py-3 font-mono text-xs font-bold" style={{ color: 'var(--text-accent)', whiteSpace: 'nowrap' }}>{r.table}</td>
                  <td className="px-4 py-3" style={{ color: 'var(--text-primary)', maxWidth: 380 }}>{r.head}</td>
                  <td className="px-4 py-3 text-right font-medium" style={{ color: r.igst > 0 ? 'var(--text-primary)' : 'var(--text-muted)' }}>{fmt(r.igst)}</td>
                  <td className="px-4 py-3 text-right font-medium" style={{ color: r.cgst > 0 ? 'var(--text-primary)' : 'var(--text-muted)' }}>{fmt(r.cgst)}</td>
                  <td className="px-4 py-3 text-right font-medium" style={{ color: r.sgst > 0 ? 'var(--text-primary)' : 'var(--text-muted)' }}>{fmt(r.sgst)}</td>
                  <td className="px-4 py-3 text-right" style={{ color: 'var(--text-muted)' }}>₹0</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
        <div className="flex items-start gap-3 px-6 py-4" style={{ borderTop: '1px solid var(--border-subtle)', background: 'rgba(245,158,11,0.06)' }}>
          <AlertCircle size={16} style={{ color: '#f59e0b', flexShrink: 0, marginTop: 2 }} />
          <p className="text-xs" style={{ color: '#d97706' }}>
            <strong>Review before filing:</strong> Outward supply figures (Table 3.1a–c) must be filled manually from your Sales Register. ITC figures are auto-calculated from your GSTR-2B reconciliation. Always verify against official GSTR-2B on the GST portal before filing.
          </p>
        </div>
      </div>
    </div>
  );
}
